#!/bin/sh
#
# Create a systemd environment file for tee-supplicant
# $1 is the path to the file to be generated.
# At the moment this figures out the --rpmb-cid parameter to be given to
# tee-supplicant, indicating which eMMC device OP-TEE should use for RPMB
# storage.
# No file is generated if no device is found (not an error) or if multiple
# eMMCs are found (which is an error).
# This script is called by the systemd tee-supplicant.service as an
# ExecStartPre entry just before starting the tee-supplicant process.

[ "$1" ] || { echo Usage: $0 FILE >&2; exit 1; }

# Take care of killing the instance of tee-supplicant started by init.cryptfs
# in the initramfs, which is not suitable for later use because it cannot
# load Trusted Applications from the root fs. This instance cannot be killed
# much sooner either, because the kernel's tpm_ftpm_tee driver needs a running
# supplicant to be able to access RPMB secure storage.
SUPP_PID=$(pgrep tee-supplicant)
[ "$SUPP_PID" ] && kill $SUPP_PID

for f in /sys/class/mmc_host/mmc*/mmc*\:*/cid; do
  # POSIX shells don't expand globbing patterns that match no file
  [ -e $f ] || exit 0
  devtype=$(echo $f | sed 's/cid/type/')
  [ ! -e $devtype ] && continue
  [ "$(cat $devtype)" != "MMC" ] && continue
  [ "$CID" ] && { echo $0: Multiple eMMC devices found, not chosing one automatically >&2; exit 2; }
  CID=$(cat $f)
done
[ "$CID" ] && echo RPMB_CID="--rpmb-cid $CID" >$1
