#!/bin/sh

# Source function library.
. /etc/init.d/functions

#----------------------------------------------------------------------
#
# supported options:
#  start
#  stop
#  restart: stops and starts mountd
#FIXME: need to create the /var/lib/nfs/... directories
case "$1" in
  start)
    /usr/bin/hciattach /dev/ttymxc3 texas 3000000 flow
	;;
  stop)
  ;;
  restart)
	$0 stop
	$0 start;;
  *)	echo "Usage: $0 {start|stop|restart}"
	exit 1;;
esac
